# Generated by Django 2.2.6 on 2019-10-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('estimated_duration', models.PositiveSmallIntegerField()),
                ('completed_duration', models.DurationField(null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed')], default=0)),
            ],
        ),
    ]
